### ISSUE TITLE
🐛 Working folder should be auto created

### ISSUE THREAD

**Issue by phatblat** [davidahouse/lynn-cli#38]
Launching in interactive mode for the first time generates an error.

```
$ lynn-cli
  _
 | |  _   _   _ __    _ __
 | | | | | | | '_ \  | '_ \
 | | | |_| | | | | | | | | |
 |_|  \__, | |_| |_| |_| |_|
      |___/
fs.js:119
    throw err;
    ^

Error: ENOENT: no such file or directory, scandir '/Users/ben/.lynn/requests'
    at Object.readdirSync (fs.js:806:3)
    at Object.listFiles (/usr/local/lib/node_modules/lynn-cli/lib/files.js:55:18)
    at Object.gatherOperations (/usr/local/lib/node_modules/lynn-cli/lib/operation.js:231:26)
    at Object.<anonymous> (/usr/local/lib/node_modules/lynn-cli/bin/lynn-cli.js:31:28)
    at Module._compile (internal/modules/cjs/loader.js:805:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:816:10)
    at Module.load (internal/modules/cjs/loader.js:672:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:612:12)
    at Function.Module._load (internal/modules/cjs/loader.js:604:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:868:12)
```

Neither `~/.lynn` nor `~/.lynn/requests` exist. Auto-create?

**Comment by davidahouse** [comment]
@phatblat Yeah that is a pretty terrible first run experience... :(
